// Write your createAdvancedCipher function here! ✨
// You'll need to export it so the tests can run it.

import { Cipher } from "./solution";

export function createAdvancedCipher(
	onVowel: Cipher,
	onConsonant: Cipher,
	onPunctuation: Cipher
) {
	//     - Parameters:
	//   1. `text`: Any string
	// - Return: A string generated by calling, on every character of `text`:
	//   - If the character is a vowel (`/[aeiou]/i`): `onVowel`
	//   - If the character is a consonant (`/[bcdfghjklmnpqrstvwxyz]/i`): `onConsonant`
	//   - For any other character: `onPunctuation`

	return (text: string) => {
		let result = "";

		for (const character of text) {
			const cipher = /[aeiou]/i.test(character)
				? onVowel
				: /[bcdfghjklmnpqrstvwxyz]/i.test(character)
				? onConsonant
				: onPunctuation;

			result += cipher(character);
		}

		return result;
	};
}
